import { Exercise, Program, Session, Supplement, DailyLog } from './types';

export const MOTIVATIONAL_QUOTES: string[] = [
  "The path to mastery is forged in sweat and discipline.",
  "A warrior's strength is not in his blade, but in his resolve.",
  "In the quiet of the dojo, find the roar of your spirit.",
  "Every drop of sweat is a weakness leaving the body.",
  "Defeat is not falling down, but refusing to get up.",
  "The body achieves what the mind believes.",
  "Discipline is the bridge between goals and accomplishment.",
  "Strength does not come from winning. Your struggles develop your strengths.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Mastery is not a destination, but a journey.",
  "Your only limit is you.",
  "Push harder than yesterday if you want a different tomorrow.",
  "Success is training, failure is learning.",
  "The warrior's mind is as sharp as his sword.",
  "Don't count the reps, make the reps count.",
  "Consistency is what transforms average into excellence.",
  "A river cuts through rock, not because of its power, but its persistence.",
  "The dojo is a mirror; it reflects your inner self.",
  "Fear is a reaction. Courage is a decision.",
  "Fall seven times, stand up eight.",
  "The will to win is important, but the will to prepare is vital.",
  "Obsessed is just a word the lazy use to describe the dedicated.",
  "What seems impossible today will one day become your warm-up.",
  "Train your mind and your body will follow.",
  "Be stronger than your strongest excuse.",
  "It's not about being the best. It's about being better than you were yesterday.",
  "The grind never stops. Neither should you.",
  "Discipline is choosing between what you want now and what you want most.",
  "Embrace the suck. It's where you grow.",
  "Victory is reserved for those who are willing to pay its price.",
  "Channel your energy, focus your mind.",
  "An amateur trains until they get it right; a professional trains until they can't get it wrong.",
  "The best workouts are the ones you didn't feel like doing.",
  "Look in the mirror... that's your competition.",
  "Strive for progress, not perfection.",
  "Pain is weakness leaving the body.",
  "The harder the battle, the sweeter the victory.",
  "Your attitude determines your direction.",
  "Go the extra mile. It's never crowded.",
  "Suffer the pain of discipline or suffer the pain of regret.",
  "Master your craft. Exceed your potential.",
  "The body is your temple. Keep it pure and clean for the soul to reside in.",
  "No citizen has a right to be an amateur in the matter of physical training.",
  "Act as if what you do makes a difference. It does.",
  "Once you learn to quit, it becomes a habit.",
  "If it doesn't challenge you, it won't change you.",
  "Don't wait for opportunity. Create it.",
  "You are what you repeatedly do. Excellence, then, is not an act, but a habit.",
  "The secret of getting ahead is getting started.",
  "You miss 100% of the shots you don't take.",
  "Sweat is just weakness leaving the body.",
  "Discipline beats motivation every single time.",
  "The body follows where the mind dares to go.",
  "Courage is a muscle — train it daily.",
  "No excuses. Only adaptation.",
  "Pain is the whisper of growth.",
  "A warrior trains when no one watches.",
  "Small steps forge great destinies.",
  "Stillness sharpens movement.",
  "Your limits are memories, not walls.",
  "Energy flows where focus goes.",
  "Every rep is a dialogue with your will.",
  "Fall seven times, rise eight — but rise stronger.",
  "Your sweat writes your story.",
  "Move with purpose, rest with honor.",
  "You don’t need motivation, you need direction.",
  "A strong body shelters a calm mind.",
  "Consistency is the highest form of mastery.",
  "The fight isn’t against others, but against your comfort.",
  "Each failure is a push-up for the soul.",
  "In stillness, the fighter breathes.",
  "One more rep — that’s where the real training begins.",
  "No rush. The mountain isn’t moving.",
  "Be patient. Steel needs time to temper.",
  "Rest isn’t weakness — it’s strategy.",
  "Let fatigue become your teacher.",
  "A disciplined life is a free life.",
  "Every movement is meditation in disguise.",
  "Less noise. More intent.",
  "You are both the forge and the blade.",
  "Respect your effort more than your result.",
  "Mastery begins where motivation ends.",
  "What you repeat, you become.",
  "Train the mind, the body will obey.",
  "In the silence between breaths, greatness grows.",
  "Do not chase power. Build presence.",
  "Sweat. Reflect. Repeat.",
  "The goal isn’t to look strong. It’s to be unshakable.",
  "No wasted motion, no wasted day.",
  "Precision is strength in disguise.",
  "Better to move slowly in the right direction than fast in circles.",
  "Make your habits your armor.",
  "Every drop of effort counts — even the invisible ones.",
  "The dojo exists wherever you stand.",
  "Still water cuts the deepest reflection.",
  "When you tire, remember why you started.",
  "Be the calm storm.",
  "Train like your future self is watching.",
  "The journey doesn’t end — it evolves."
];

export const DAILY_REFLECTIONS: string[] = [
    "Quelle est la plus grande victoire que vous ayez remportée sur vous-même récemment ?",
    "Comment transformez-vous un échec en une leçon pour votre prochain entraînement ?",
    "Quelle discipline apprise au dojo appliquez-vous dans votre vie quotidienne ?",
    "Visualisez votre objectif ultime. Quelle petite étape pouvez-vous franchir aujourd'hui pour vous en approcher ?",
    "La patience est une arme. Dans quel domaine de votre entraînement devez-vous en faire preuve ?",
    "Aujourd'hui, comment pouvez-vous transformer un obstacle en opportunité ?",
    "Quelle est la 'répétition' la plus difficile que vous devez faire en dehors du dojo ?",
    "Si votre motivation était un muscle, quel exercice la renforcerait aujourd'hui ?",
    "Pensez à votre dernière séance difficile. Quelle force mentale avez-vous découverte ?",
    "La récupération est aussi un art. Comment allez-vous honorer votre repos aujourd'hui ?",
    "Quelle est la petite victoire que vous visez aujourd'hui ?",
    "Comment le calme de votre esprit peut-il améliorer la puissance de votre corps ?",
    "Quelle habitude pourriez-vous commencer aujourd'hui pour être plus fort demain ?",
    "La constance est la clé. Quel est votre plan pour rester constant cette semaine ?",
    "Comment votre nutrition soutient-elle vos efforts au dojo ?",
    "Quel est le plus grand mythe sur la force que vous avez déconstruit ?",
    "Si vous pouviez donner un conseil à celui que vous étiez il y a un an, quel serait-il ?",
    "Quelle est la différence entre l'effort et l'acharnement dans votre pratique ?",
    "Comment gérez-vous les jours où l'envie de s'entraîner n'est pas là ?",
    "Quelle partie de votre entraînement vous apporte le plus de joie ?",
    "L'humilité est une force. Qu'avez-vous appris de quelqu'un d'autre récemment ?",
    "Comment mesurez-vous le progrès au-delà des chiffres et des poids ?",
    "Quel est votre 'pourquoi' ? Qu'est-ce qui vous pousse à enfiler vos chaussures de sport ?",
    "Comment l'entraînement a-t-il changé votre perception de la douleur ou de l'inconfort ?",
    "Quelle est la chose la plus importante que votre corps vous ait apprise ?",
    "De quelle manière votre entraînement est-il une forme de méditation active ?",
    "Comment célébrez-vous vos accomplissements, petits et grands ?",
    "Quel aspect de votre mental a le plus besoin d'entraînement en ce moment ?",
    "La peur peut être un carburant. Quelle peur allez-vous affronter aujourd'hui ?",
    "Comment maintenez-vous l'équilibre entre entraînement, travail, et vie personnelle ?",
    "Quelle est la critique la plus constructive que vous ayez reçue ?",
    "Comment votre environnement (le dojo, votre maison) influence-t-il votre discipline ?",
    "Quelle est une croyance limitante que vous êtes prêt à abandonner ?",
    "Le respect se gagne. Comment montrez-vous du respect pour votre corps ?",
    "Quel est le rôle de la musique ou du silence dans votre concentration ?",
    "Si vous deviez décrire votre parcours de fitness en trois mots, quels seraient-ils ?",
    "Comment restez-vous curieux et ouvert à de nouvelles méthodes d'entraînement ?",
    "Quel est votre rituel avant ou après l'entraînement pour vous centrer ?",
    "Comment la discipline physique renforce-t-elle votre discipline mentale ?",
    "Quel est le plus grand sacrifice que vous ayez fait pour vos objectifs de fitness ?",
    "Comment transformez-vous la jalousie ou la comparaison en inspiration ?",
    "Quel est le meilleur conseil que vous n'ayez jamais suivi ?",
    "Comment votre corps vous remercie-t-il lorsque vous prenez soin de lui ?",
    "Quelle est la compétence que vous souhaitez le plus maîtriser cette année ?",
    "Comment la visualisation vous aide-t-elle à atteindre vos performances cibles ?",
    "Quelle est la conversation la plus importante que vous ayez eue avec vous-même pendant un effort intense ?",
    "Comment votre entraînement vous aide-t-il à être une meilleure personne en dehors du dojo ?",
    "Quelle est votre définition personnelle du succès dans ce parcours ?",
    "Comment le repos et le sommeil sont-ils des armes secrètes dans votre arsenal ?",
    "Quelle est la prochaine frontière que vous voulez repousser ?",
    "Aujourd’hui, tu n’as pas combattu ton adversaire. Tu as combattu ta paresse. Qui a gagné ?",
    "Quand as-tu cessé d’écouter ton corps ? Il te parle, mais tu le fais taire sous le bruit de tes pensées.",
    "Ton programme d’entraînement n’a pas besoin d’être parfait. Toi non plus. Il doit juste exister.",
    "Tu cherches la motivation ? Elle se cache derrière ta première action.",
    "Si tu veux progresser, regarde moins les autres et plus ton rythme.",
    "Ton corps se transforme à la vitesse de ta patience.",
    "La fatigue est un signal, pas une faiblesse. Sais-tu la lire ?",
    "Chaque séance est une lettre adressée à ton futur toi. Que lui écris-tu aujourd’hui ?",
    "L’échec répété forge l’attention. L’attention forge la maîtrise.",
    "Ne te bats pas contre la douleur, danse avec elle.",
    "Tu veux plus de résultats ? Commence par plus d’intention.",
    "Le Sensei t’observe : pas pour juger, mais pour voir si tu écoutes enfin ton souffle.",
    "Le progrès est discret, presque timide. Il déteste les impatients.",
    "Pourquoi veux-tu aller vite ? La force ne se télécharge pas, elle s’incarne.",
    "Le confort est un ennemi poli : il te sourit pendant qu’il t’endort.",
    "Ce que tu ne maîtrises pas aujourd’hui deviendra ton terrain d’excellence demain.",
    "L’eau ne lutte pas contre la pierre. Elle la sculpte.",
    "Tu veux de la force ? Commence par l’humilité.",
    "Chaque pause est une opportunité de te recentrer, pas de t’échapper.",
    "Répéter n’est pas ennuyant. C’est prier en mouvement.",
    "L’esprit veut abandonner bien avant que le corps n’ait vraiment souffert.",
    "Sais-tu pourquoi tu t’entraînes, ou cherches-tu encore à le découvrir ?",
    "Plus tu maîtrises ton souffle, moins le monde te contrôle.",
    "La vraie victoire, c’est celle contre le lendemain annulé.",
    "Observe ton reflet après la séance. C’est ton effort, pas ton miroir, qui brille.",
    "La rigueur est une forme d’amour envers soi-même.",
    "Si tu ne choisis pas ta difficulté, la vie le fera pour toi.",
    "L’énergie ne se perd jamais : elle change d’intention.",
    "Fais de ton entraînement un rituel, pas une corvée.",
    "Le muscle se répare la nuit. Le mental, au silence.",
    "L’ego soulève lourd. Le maître soulève juste.",
    "Ne confonds pas intensité et chaos.",
    "Ce que tu appelles discipline, d’autres appellent paix.",
    "Arrête de te promettre. Commence à te prouver.",
    "Ton énergie du matin est ton sabre. Aiguise-la.",
    "Tu cherches la motivation ? Respire plus lentement.",
    "Un corps en tension révèle un esprit dispersé.",
    "Le Sensei ne t’apprend pas à frapper. Il t’apprend à ne plus fuir.",
    "La maîtrise ne se voit pas. Elle se ressent.",
    "Ne cherche pas la perfection. Cherche la précision.",
    "Plus tu simplifies, plus tu deviens fort.",
    "Un jour sans discipline est une conversation manquée avec toi-même.",
    "Les excuses ne brûlent pas de calories.",
    "La peur de l’échec est un luxe que le guerrier ne s’offre plus.",
    "Quand tu dis ‘j’ai pas le temps’, le temps t’écoute — et s’en va.",
    "Celui qui s’entraîne sans plaisir s’épuise. Celui qui s’entraîne avec conscience s’élève.",
    "Tes muscles n’oublient rien. Chaque effort laisse une empreinte.",
    "Le dojo n’est pas un lieu, c’est une attitude.",
    "Sois exigeant, mais reste doux avec toi-même.",
    "À force d’entretenir ton feu, tu deviendras lumière pour les autres."
];


export const MOCK_EXERCISES: Exercise[] = [
    { id: 'ex1', name: 'Kettlebell Thruster', equipment: ['kettlebell'], muscles: ['quads', 'glutes', 'shoulders'] },
    { id: 'ex2', name: 'Hammer Curl', equipment: ['dumbbells', 'kettlebell'], muscles: ['biceps'] },
    { id: 'ex3', name: 'Kettlebell Halo', equipment: ['kettlebell'], muscles: ['shoulders', 'core'] },
    { id: 'ex4', name: 'Kettlebell Swing', equipment: ['kettlebell'], muscles: ['glutes', 'hamstrings', 'back'] },
    { id: 'ex5', name: 'RDL to Squat', equipment: ['kettlebell'], muscles: ['hamstrings', 'quads', 'glutes'] },
    { id: 'ex6', name: 'Kettlebell Snatch', equipment: ['kettlebell'], muscles: ['full-body'] },
    { id: 'ex7', name: 'Push-up', equipment: ['none'], muscles: ['chest', 'triceps', 'shoulders'] },
    { id: 'ex8', name: 'Pull-up', equipment: ['pull-up bar'], muscles: ['back', 'biceps'] },
    { id: 'ex9', name: 'Bodyweight Squat', equipment: ['none'], muscles: ['quads', 'glutes'] },
    { id: 'ex10', name: 'Running', equipment: ['none'], muscles: ['legs', 'cardio'] },
    { id: 'ex11', name: 'Lunges Overhead Press', equipment: ['kettlebell'], muscles: ['legs', 'shoulders'] },
    { id: 'ex12', name: 'Swing to Squat', equipment: ['kettlebell'], muscles: ['glutes', 'quads'] },
    { id: 'ex13', name: 'Clean to Rotational Press', equipment: ['kettlebell'], muscles: ['full-body', 'core'] },
    { id: 'ex14', name: 'Over Shoulder Toss', equipment: ['kettlebell'], muscles: ['full-body', 'core'] },
    { id: 'ex15', name: 'Kettlebell Pullover', equipment: ['kettlebell'], muscles: ['chest', 'lats'] },
    { id: 'ex16', name: 'Hand to Hand', equipment: ['kettlebell'], muscles: ['core', 'grip'] },
    { id: 'ex17', name: 'Around The Body Lunges', equipment: ['kettlebell'], muscles: ['legs', 'core'] },
    { id: 'ex18', name: 'Hammer to Overhead Press', equipment: ['kettlebell'], muscles: ['biceps', 'shoulders'] },
    { id: 'ex19', name: 'Halo Press Out', equipment: ['kettlebell'], muscles: ['shoulders', 'core'] },
    { id: 'ex20', name: 'Around The Body to Lunge', equipment: ['kettlebell'], muscles: ['legs', 'core'] },
    { id: 'ex21', name: 'Push-Up Pull Through', equipment: ['kettlebell'], muscles: ['chest', 'core', 'back'] },
    { id: 'ex22', name: 'Pop Squat', equipment: ['kettlebell'], muscles: ['legs', 'cardio'] },
    { id: 'ex23', name: 'Figure Eight', equipment: ['kettlebell'], muscles: ['core', 'legs'] },
    { id: 'ex24', name: 'Squat to Pullover', equipment: ['kettlebell'], muscles: ['legs', 'chest', 'lats'] },
    { id: 'ex25', name: 'Deadlift High Pull', equipment: ['kettlebell'], muscles: ['hamstrings', 'glutes', 'shoulders'] },
    { id: 'ex26', name: 'Digging Halo', equipment: ['kettlebell'], muscles: ['core', 'shoulders'] },
    { id: 'ex27', name: 'Lunges Pass Through', equipment: ['kettlebell'], muscles: ['legs', 'core'] },
    { id: 'ex28', name: 'Rotational Swing', equipment: ['kettlebell'], muscles: ['glutes', 'core'] },
    { id: 'ex29', name: 'Kettlebell Reverse Curl', equipment: ['kettlebell'], muscles: ['biceps'] },
    { id: 'ex30', name: 'Rotational Halo', equipment: ['kettlebell'], muscles: ['core', 'shoulders'] },
    { id: 'ex31', name: 'Around The Body with Rotational', equipment: ['kettlebell'], muscles: ['core'] },
];

export const MOCK_PROGRAMS: Program[] = [
    {
        id: 'prog1',
        name: 'Kettlebell Neon Workout',
        mode: 'sets',
        rounds: 3,
        restBetweenRoundsSec: 60,
        category: ['HIIT', 'Full-Body'],
        equipment: ['kettlebell'],
        estDurationMin: 25,
        intensity: 4,
        exercises: [
            { exerciseId: 'ex1', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex4', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex5', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex6', target: { timeSec: 30 }, restSec: 30 },
        ]
    },
    {
        id: 'prog2',
        name: 'Dojo Bodyweight Basics',
        mode: 'series',
        category: ['Street-Workout', 'Full-Body'],
        equipment: ['none', 'pull-up bar'],
        estDurationMin: 45,
        intensity: 3,
        exercises: [
            { exerciseId: 'ex8', target: { reps: 8 }, sets: 3, restSec: 90 },
            { exerciseId: 'ex7', target: { reps: 15 }, sets: 3, restSec: 60 },
            { exerciseId: 'ex9', target: { reps: 20 }, sets: 3, restSec: 60 },
        ]
    },
    {
        id: 'prog3',
        name: 'Quick Burn',
        mode: 'sets',
        rounds: 4,
        restBetweenRoundsSec: 45,
        category: ['Cardio', 'HIIT'],
        equipment: ['none'],
        estDurationMin: 15,
        intensity: 5,
        exercises: [
            { exerciseId: 'ex9', target: { timeSec: 20 }, restSec: 10 },
            { exerciseId: 'ex7', target: { timeSec: 20 }, restSec: 10 },
        ]
    },
    {
        id: 'prog4',
        name: 'Morning Run',
        mode: 'series',
        category: ['Running'],
        equipment: ['none'],
        estDurationMin: 30,
        intensity: 3,
        exercises: [
            { exerciseId: 'ex10', target: { timeSec: 1800 } }
        ]
    },
    {
        id: 'prog5',
        name: 'Fusion Kettlebell Dynamique',
        mode: 'sets',
        rounds: 3,
        restBetweenRoundsSec: 60,
        category: ['Kettlebell', 'Full-Body'],
        equipment: ['kettlebell'],
        estDurationMin: 20,
        intensity: 4,
        exercises: [
            { exerciseId: 'ex11', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex2', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex12', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex13', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex14', target: { timeSec: 30 }, restSec: 30 },
        ]
    },
    {
        id: 'prog6',
        name: 'Circuit du Guerrier Kettlebell',
        mode: 'sets',
        rounds: 3,
        restBetweenRoundsSec: 60,
        category: ['Kettlebell', 'Core Strength'],
        equipment: ['kettlebell'],
        estDurationMin: 20,
        intensity: 3,
        exercises: [
            { exerciseId: 'ex15', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex16', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex17', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex18', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex19', target: { timeSec: 30 }, restSec: 30 },
        ]
    },
    {
        id: 'prog7',
        name: 'Blitz Total Body',
        mode: 'sets',
        rounds: 3,
        restBetweenRoundsSec: 60,
        category: ['Kettlebell', 'Full-Body', 'HIIT'],
        equipment: ['kettlebell'],
        estDurationMin: 20,
        intensity: 5,
        exercises: [
            { exerciseId: 'ex1', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex2', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex20', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex6', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex21', target: { timeSec: 30 }, restSec: 30 },
        ]
    },
    {
        id: 'prog8',
        name: 'HIIT Inferno Kettlebell',
        mode: 'sets',
        rounds: 3,
        restBetweenRoundsSec: 60,
        category: ['Kettlebell', 'HIIT', 'Cardio'],
        equipment: ['kettlebell'],
        estDurationMin: 20,
        intensity: 5,
        exercises: [
            { exerciseId: 'ex22', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex23', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex24', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex25', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex26', target: { timeSec: 30 }, restSec: 30 },
        ]
    },
    {
        id: 'prog9',
        name: 'La Forge de la Force',
        mode: 'series',
        category: ['Kettlebell', 'Strength'],
        equipment: ['kettlebell'],
        estDurationMin: 35,
        intensity: 4,
        exercises: [
            { exerciseId: 'ex1', target: { reps: 15 }, sets: 3, restSec: 60 },
            { exerciseId: 'ex27', target: { reps: 15 }, sets: 3, restSec: 60 },
            { exerciseId: 'ex28', target: { reps: 15 }, sets: 3, restSec: 60 },
            { exerciseId: 'ex5', target: { reps: 15 }, sets: 3, restSec: 60 },
            { exerciseId: 'ex29', target: { reps: 15 }, sets: 3, restSec: 60 },
            { exerciseId: 'ex3', target: { reps: 15 }, sets: 3, restSec: 60 },
        ]
    },
    {
        id: 'prog10',
        name: 'Tempête Rotative Kettlebell',
        mode: 'sets',
        rounds: 3,
        restBetweenRoundsSec: 60,
        category: ['Kettlebell', 'Core', 'Functional'],
        equipment: ['kettlebell'],
        estDurationMin: 20,
        intensity: 4,
        exercises: [
            { exerciseId: 'ex30', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex14', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex2', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex6', target: { timeSec: 30 }, restSec: 30 },
            { exerciseId: 'ex31', target: { timeSec: 30 }, restSec: 30 },
        ]
    },
];

const d = new Date();
const d1 = new Date(d); d1.setDate(d.getDate() - 2);
const d2 = new Date(d); d2.setDate(d.getDate() - 1);
const d3 = new Date(d); d3.setDate(d.getDate()); // Today
const ds1 = d1.toISOString().split('T')[0];
const ds2 = d2.toISOString().split('T')[0];
const ds3 = d3.toISOString().split('T')[0];

export const MOCK_DAILY_LOGS: Record<string, DailyLog> = {
  [ds1]: {
    date: ds1,
    sessions: [{ id: 'sess1', programName: 'Kettlebell Neon Workout', date: d1, xpGained: 120, totalVolumeKg: 1500 }],
    hydration: 2500,
    supplementLog: { 'creatine': true, 'omega3': true, 'ashwagandha': false }
  },
  [ds2]: {
    date: ds2,
    sessions: [{ id: 'sess2', programName: 'Morning Run', date: d2, xpGained: 50, distanceKm: 5 }],
    hydration: 3000,
    supplementLog: { 'creatine': true, 'omega3': true, 'ashwagandha': true }
  },
  [ds3]: {
    date: ds3,
    sessions: [],
    hydration: 1250,
    supplementLog: { 'creatine': true, 'omega3': false, 'ashwagandha': false }
  }
};


export const INITIAL_SUPPLEMENTS: Supplement[] = [
  { id: 'creatine', name: 'Creatine (Creapure®)', dosage: '5 gélules ≈ 2,5g', time: 'Matin' },
  { id: 'omega3', name: 'Oméga-3 (EPA/DHA)', dosage: '2 gélules', time: 'Déjeuner' },
  { id: 'ashwagandha', name: 'Ashwagandha (KSM-66)', dosage: '1 gélule', time: 'Soir', notes: 'Cycle 2–3 mois, puis pause 2 sem.' },
];

export const XP_PER_LEVEL = (level: number) => Math.round(150 * Math.pow(level, 1.35) + 200);
